version: '3'

services:
    redis_session:
        image: "redis:latest"
        ports:
            - "6379:6379"
        volumes:
            - "./data/redis:/data/redis"

    postgresql:
        image: "postgres:latest"
        ports:
            - "5432:5432"
        volumes:
            - "./postgres/init:/data/postgresql"
        environment:
            POSTGRES_USER: shumiya
            POSTGRES_PASSWORD: shumiya
            POSTGRES_DB: shumi_db
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

    shumipro_api:
        image: "shumipro_api:latest"
        ports:
            - "8080:8080"
        volumes:
            - "./shumipro_api:/app"
        environment:
            SPRING_PROFILES_ACTIVE: docker

    shumipro_front:
        image: node:14.15.5
        ports:
            - "3000:3000"
        working_dir: /app
        volumes:
            - "./shumipro_front:/app"
        command: [sh, -c, npm install -D webpack && npm install && npm run export && npm run start]
        
    nginx:
        image: "nginx:latest"
        ports:
            - 80:80
        volumes:
            - ./shumipro_front/out:/var/www
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - shumipro_front