version: '3'

services:
    redis_session:
        image: "redis:latest"
        ports:
            - "6379:6379"
        volumes:
            - "./data/redis:/data/redis"

    postgresql:
        image: "postgres:latest"
        ports:
            - "5432:5432"
        volumes:
            - "./postgres/init:/data/postgresql"
        environment:
            POSTGRES_USER: $DB_USERNAME
            POSTGRES_PASSWORD: $DB_PASSWORD
            POSTGRES_DB: shumi_db
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

    shumipro_api:
        image: zenika/kotlin:latest
        ports:
            - "8080:8080"
        working_dir: /app
        volumes:
            - "./shumipro_api:/app"
        environment:
            SPRING_PROFILES_ACTIVE: docker
            DB_USERNAME: $DB_USERNAME
            DB_PASSWORD: $DB_PASSWORD
            FRONT_ORIGIN: $FRONT_ORIGIN
            API_TOKEN_SECRET_KEY: $API_TOKEN_SECRET_KEY
        command: ["java", "-jar", "shumipro_api-0.0.1-SNAPSHOT.war"]

    shumipro_front:
        image: node:14.15.5
        ports:
            - "3000:3000"
        working_dir: /app
        volumes:
            - "./shumipro_front:/app"
        environment:
            NEXT_PUBLIC_API_SERVER: $NEXT_PUBLIC_API_SERVER
        command: [sh, -c, npm install -D webpack && npm install && npm build && npm run start]

    nginx:
        image: "nginx:latest"
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./shumipro_front/out:/var/www/html
            - ./nginx:/etc/nginx/conf.d
            - ./letsencrypt:/etc/letsencrypt
        depends_on:
            - shumipro_front

    certbot:
        image: certbot/certbot:v1.7.0
        volumes:
            - ./letsencrypt:/etc/letsencrypt
            - ./shumipro_front/out:/var/www/html
        command: ["--version"]

