version: '3'

services:
    redis_session:
        image: "redis:latest"
        ports:
            - "6379:6379"
        volumes:
            - "./data/redis:/data/redis"

    postgresql:
        image: "postgres:latest"
        ports:
            - "5432:5432"
        volumes:
            - "./postgres/init:/data/postgresql"
        environment:
            POSTGRES_USER: shumiya
            POSTGRES_PASSWORD: shumiya
            POSTGRES_DB: shumi_db
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

    shumipro_api:
        image: "shumipro_api:latest"
        ports:
            - "8080:8080"
        volumes:
            - ".:/app"
        environment:
            SPRING_PROFILES_ACTIVE: docker
        links:
            - redis_session
            - postgresql
            - shumipro_front

    shumipro_front:
        image: "shumipro_front:latest"
        ports:
            - "3000:3000"
        volumes:
            - ".:/app"
        links:
            - shumipro_api
