name: EC2 auto deploy

on:
  pull_request:
    branches:
      - master
    types: [closed]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Public IP Install
        id: ip
        uses: haythem/public-ip@v1.2
        
      - name: Checkout
        uses: actions/checkout@v2

      - name: AWS CLI install
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version
          
