name: EC2 auto deploy

on:
  pull_request:
    branches:
      - master
    types: [closed]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Public IP Install
        id: ip
        uses: haythem/public-ip@v1.2
