name: EC2 auto deploy

on:
  pull_request:
    branches:
      - master
    types: [closed]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Public IP Install
        id: ip
        uses: haythem/public-ip@v1.2
        
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: |
         echo "${{ secrets.TASK_MANAGER_KEY }}" > private_key
         chmod 600 private_key
         ssh -oStrictHostKeyChecking=no ${{ secrets.EC2_USER_NAME }}@${{ secrets.EC2_HOST_NAME }} -i private_key "sh /home/app_admin/app/deployTest.sh"
